### ISSUE TITLE
Customer Agent throws error

### ISSUE THREAD

**Issue by janl1992** [HBRS-MAAS/project#101]
The Customer Agent throws errors - are you aware of this?
org.json.JSONException: JSONObject["bakery-005"] not found.
	at org.json.JSONObject.get(JSONObject.java:566)
	at org.json.JSONObject.getJSONObject(JSONObject.java:778)
	at org.team_pjt.agents.CustomerAgent.findTheCheapest(CustomerAgent.java:495)
	at org.team_pjt.agents.CustomerAgent.access$1000(CustomerAgent.java:40)
	at org.team_pjt.agents.CustomerAgent$SendConfirmation.action(CustomerAgent.java:324)
	at jade.core.behaviours.Behaviour.actionWrapper(Behaviour.java:344)
	at jade.core.Agent$ActiveLifeCycle.execute(Agent.java:1585)
	at jade.core.Agent.run(Agent.java:1524)
	at java.lang.Thread.run(Thread.java:745)

**Comment by widyaaulia** [comment]
That was one that we corrected in our last pull request to develop which hasn't been merged yet. I will check if the problem still appears now.

**Comment by janl1992** [comment]
Okay with the latest changes in hers/project the error is gone thanks.
